# load data.table and bit64 for data.table::fread
# and to sink any warnings about column type
library(data.table)
library(bit64)
library(ggplot2) # for QQ & CDF plots

# load all data
method1Sample <- fread("../data/rand1.txt")
method2Sample <- fread("../data/rand2.txt")

# calculate time diff's between the column entries
method1ShiftedSample <- # artifically shift scale to the left
  as.integer(method1Sample[,  V1 - V1[1]])

method2ShiftedSample <- 
  as.integer(method2Sample[,  V1 - V1[1]])

# throw out first observation from method1 to make sample size equal
deltaTime <- rbindlist(
 list(data.table(method = "1", dT = diff(method1ShiftedSample)[-1]),
      data.table(method = "2", dT = diff(method2ShiftedSample))
      ))

# plot dT's to do a smell test:
cdfPlot <- ggplot(data = deltaTime,
		  aes(x = dT, color = method)) +
	   stat_ecdf() +
	   labs(x = "time between random data, dT (secs)",
		y = "Probability that dT is < x",
		title = "Empirical CDFs generated by two methods") +
	   theme_bw()

ggsave(filename = "../plots/ecdf.png",
       plot = cdfPlot,
       width = 5,
       height = 5,
       units = "in",
       dpi = 300)

hists <- ggplot(data = deltaTime,
		aes(x = dT, color = method, fill = method)) +
	 stat_density(alpha = 0.5,
		      adjust = 0.65) + 
	 labs(x = "time between random data, dT (secs)",
	      y = "estimated P(dT = x)",
	      title = "Density estimates for two methods") +
	 theme_bw()

ggsave(filename = "../plots/densities.png",
       plot = hists,
       width = 5,
       height = 5,
       units = "in",
       dpi = 300)



ks.test(x = deltaTime[method == "1", dT],
	y = deltaTime[method == "2", dT],
	alternative = "two",
	exact = FALSE)

